import Head from "next/head";
import FrontPage from "../Components/FrontPage";






export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Anand Pandey || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FrontPage/>
     
      
      

     
      
    </div>
  );
}
